package com.project.why.braillelearning.EnumConstant;

/**
 * Created by hyuck on 2017-09-24.
 */

/**
  Menu의 이름들을 정의해논 enum
 */
public enum Menu {
    TUTORIAL,
    BASIC,
    MASTER,
    TRANSLATION,
    QUIZ,
    MYNOTE,
    COMMUNICATION,

    INITIAL_BASIC,
    VOWEL_BASIC,
    FINAL_BASIC,
    NUMBER_BASIC,
    ALPHABET_BASIC,
    SENTENCE_BASIC,
    ABBREVIATION_BASIC,

    LETTER_MASTER,
    WORD_MASTER,

    INITIAL_QUIZ,
    VOWEL_QUIZ,
    FINAL_QUIZ,
    NUMBER_QUIZ,
    ALPHABET_QUIZ,
    SENTENCE_QUIZ,
    ABBREVIATION_QUIZ,
    LETTER_QUIZ,
    WORD_QUIZ,

    BASIC_MYNOTE,
    MASTER_MYNOTE,
    COMMUNICATION_MYNOTE,

    TEACHER_COMMUNICATION,
    STUDENT_COMMUNICATION,
}
